- .gitignore
This tries to make it be the case that `git status` on a repo where the release tarball has been unpacked and a build has been done but no other changes have been made will be completely quiet.
In particular ignore the darwin headers directories which come from
the release tarballs, and additionally ignore some object files in the AltConsole, and some
extra places where fasls seem to end up when rebuilding.
Note: this has only been checked on a Mac: there may be similar changes needed for other platforms.  Sorry.
> gitignore: ignore some more ephemera

- .gitignore
I build the CCL GUI application just by `(require :cocoa-application)` on OSX, which leaves `Clozure CL64.app` (or equivalent 32-bit app) in the top directory of the repo.  This tries to ignore that.
Note I am not sure I am building the app the right way: this is how I've always done it but I don't know why or if there is a better way which doesn't leave it in the repo.  So this might not be needed.
> Ignore the built application on OSX

- level-0/l0-bignum64.lisp
%bignum-random wasn't normalizing its bignums before passing them to MOD (aka REM).
Luckily the current implementation of REM managed to ignore the bogosity and happened fix up the result, at least in the 64 bit version.  Perhaps 32 bit version wasn't as lucky -- see ticket 1403 in trac.  Note however that this change is in l0-bignum64 only.  I can't find the 32 bit version of %bignum-random, so I couldn't fix it.
> In %bignum-random, normalize generated bignum

- lisp-kernel/pmcl-kernel.c
Just calling realpath(3) on the value of argv[0] is inadequate.
See #38.
> In determine_executable_name, use sysctl(3) on FreeBSD

- lib/macros.lisp
ccl:arglist would have the unexpected side effect of semi-randomly
interning symbols found in macro lambda lists. This change ensures that
symbols are only interned in packages where they have actually been used.
See http://lisptips.com/post/20871695085/printing-package-qualified-symbols
See Also: #44
> defmacro - record fully qualified argstring

- lisp-kernel/win64/Makefile
See https://github.com/Clozure/ccl/issues/55
Checked with visual studio's dumpbin.exe. 32 bit ccl doesn't require libpthread-1.dll. But 64 bit ccl does. It's added by mingw64-x86_64-gcc. After static link it, now it's able to run wx86cl64 with only ccl image
Reference:
https://stackoverflow.com/questions/13768515/how-to-do-static-linking-of-libwinpthread-1-dll-in-mingw
> fix need libpthread-1.dll in windows 64 build

- lisp-kernel/win32/Makefile
- lisp-kernel/win64/Makefile
Msys2 is now very popular and I saw there are lispers comments in issues that they also use msys2 instead of cygwin. Compare to cygwin, it has pacman as package management tool, but less POSIX support. And msys2 is official recommended way to install gnu emacs on windows, so I believe there're many lisp programmers using msys2. For building ccl in msys2, it doesn't have many difference than cygwin so I modify Makefile and provide a instruction in comment. Tested on both cygwin and msys2 after modification. Because https://github.com/Clozure/ccl/pull/57 is still under discussion, currently only modify win32 Makefile.
> building in both cygwin and msys2

- level-1/l1-streams.lisp
Right now, `fd-stream-eofp` just checks the `iobuffer-eof` flag. This is wrong because the only function that sets this flag is `fd-stream-advance`, which isn't called unless we actually try to read from the stream.
For instance, open an empty file and immediately call `stream-eofp`: you get NIL.
> Make FD-STREAM-EOFP reliably return T when at EOF.

- level-1/l1-streams.lisp
`stream-eofp` on a concatenated stream can return `t` even though `stream-eofp` on one of the underlying streams returns `nil`.
For instance, for a concatenated stream `cs` whose only underlying stream is a socket `s` on which no input is available but which is still open, `(stream-eofp s)` correctly returns `nil`, but `(stream-eofp cs)`
returns `t`.
This is because `(stream-eofp cs)` calls `(stream-listen s)`, which (correctly) returns `nil`, from which `stream-eofp` (incorrectly) deduces that `s` is at end of file.
This is wrong, because `stream-listen` cannot detect EOF; use `stream-eofp` on the underlying stream instead.
> Fix stream-eofp on concatenated streams.

- level-1/l1-streams.lisp
When calling `stream-listen` on a concatenated stream `cs` with an underlying stream `s`, if `(stream-listen s)` returns `nil`, then `s` is discarded and the function continues with the next underlying stream in `cs`.
This is wrong: `s` should only be discarded when its end of file has been reached, which is in general not the same thing as `listen` returning `nil`.
> Fix STREAM-LISTEN on concatenated streams.

- lisp-kernel/lisp-debug.c
- lisp-kernel/platform-linuxx8632.h
- lisp-kernel/platform-linuxx8664.h
- lisp-kernel/pmcl-kernel.c
- lisp-kernel/thread_manager.c
- lisp-kernel/x86-exceptions.c
In addition to using ucontext_t, fix a couple of build warnings involving implicitly-declared functions.
> use ucontext_t instead of struct ucontext on Linux

- lisp-kernel/darwinx8632/Makefile
- lisp-kernel/darwinx8664/Makefile
- lisp-kernel/freebsdx8632/Makefile
- lisp-kernel/freebsdx8664/Makefile
- lisp-kernel/linuxarm/Makefile
- lisp-kernel/linuxarm64/Makefile
- lisp-kernel/linuxppc/Makefile
- lisp-kernel/linuxppc64/Makefile
- lisp-kernel/linuxx8632/Makefile
- lisp-kernel/linuxx8664/Makefile
- lisp-kernel/lisp-debug.c
- lisp-kernel/solarisx64/Makefile
- lisp-kernel/solarisx86/Makefile
- lisp-kernel/win32/Makefile
- lisp-kernel/win64/Makefile
Use git describe --dirty instead.  The idea behind this is for the
lisp kernel debugger to be able to print out the revision of the
source code that was used to build it (via the "v" debugger command).
(ref #75)
> Don't use svnversion in kernel makefiles

- level-1/l1-lisp-threads.lisp
- level-1/l1-processes.lisp
On Linux only, this patch uses `pthread_setname_np` to make the names of Lisp threads visible to standard Linux tools (e.g. GDB, htop).
I hacked this in for myself, but I thought it might be useful for others.
> Expose Lisp thread names to Linux

- lib/format.lisp
In format-logical-block, the check for non-empty *format-arguments* should
only happen in the (not asign) case. Per GZ.
Fixes Issue #112.
> Fix issue #112

- doc/manual/build.ccldoc
- a tiny typo in bootstrapping description
- reference to Subversion changed to GitHub
> Minor updates to build.ccldoc

- lib/lists.lisp
- lib/sequences.lisp
http://www.lispworks.com/documentation/HyperSpec/Issues/iss345.htm that :test and :test-not can be passed, but not both.
Should fix #152 
Test with ansi-suite gives 56 errors before and after the fix
```lisp
(mismatch '(1 2 3) '(2 3 4) :test-not #'eq :key #'oddp :test #'eq) ;should fail
(remove-duplicates "abca" :test-not #'(lambda (x y) (not (eql x y)))) ;fails; see fix
(search "dog" "it's a dog's life" :test-not #'string= :test #'string=) ;;;should fail
(substitute 9 3 '(1 2 4 1 3 4 5) :test-not #'> :test #'=) ;;should fail
(tree-equal '(1 (1 2)) '(1 (1 2)) :test-not 'eq :test 'eq) ;;; should fail
(delete-duplicates "abca" :test-not #'(lambda (x y) (not (eql x y)))) ;;; legal, but fails
````
> Check for all functions of

- lib/sequences.lisp
Fixed #132 
```lisp
? (mismatch '(a b) '(a b c) :key nil)
2
? 
? (run-tests)
Doing 21904 pending tests of 21904 tests total.
Invoking restart: #<RESTART CL-TEST::FOO #x1C3C15D>
Invoking restart: #<RESTART CL-TEST::FOO #x1C3C15D>
Invoking restart: #<RESTART CL-TEST::FOO #x1C3C15D>
Invoking restart: #<RESTART CL-TEST::FOO #x1C3C15D>
Invoking restart: #<RESTART CL-TEST::FOO #x1C3C15D>
=============== All tests succeeded ===============
(FUNCALL DO-TESTS :COMPILE COMPILE :VERBOSE VERBOSE :CATCH-ERRORS T)
took 169,940,971 microseconds (169.940980 seconds) to run.
2,389,930 microseconds (  2.389930 seconds, 1.41%) of which was spent in GC.
During that period, and with 8 available CPU cores,
158,033,785 microseconds (158.033780 seconds) were spent in user mode
11,925,601 microseconds ( 11.925601 …
```
> Assure that :key is not nil, even with :key nil

- level-1/l1-utils.lisp
Fixes:
```lisp
(let ((*gensym-counter* -1))
(gensym))
(let ((*gensym-counter* (1- most-negative-fixnum)))
(gensym))
````
Should all signal a type-error
see https://gitlab.common-lisp.net/ansi-test/ansi-test/merge_requests/19
Did rebuild ccl and run the tests:
```lisp
? (run-tests)
Doing 21904 pending tests of 21904 tests total.
Invoking restart: #<RESTART CL-TEST::FOO #x143C15D>
Invoking restart: #<RESTART CL-TEST::FOO #x143C15D>
Invoking restart: #<RESTART CL-TEST::FOO #x143C15D>
Invoking restart: #<RESTART CL-TEST::FOO #x143C15D>
Invoking restart: #<RESTART CL-TEST::FOO #x143C15D>
=============== All tests succeeded ===============
````
> Fix wrong bindings of *gensym-counter* in gensym

- level-1/l1-symhash.lisp
- lib/macros.lisp
> WITH-STANDARD-IO-SYNTAX: do not use PLN lookup

- lisp-kernel/pmcl-kernel.c
Fixes #24.
Given its name, I can infer that `lazarus` is mean to resurrect a dying thread if it still has a TCR: if TCR exists, then it calls start_lisp; if it doesn't, then it does nothing. start_lisp, in turn, is an assembly function that has the following comment inside it:
>  This is called from C code when a thread (including the initial thread) starts execution.  (Historically, it also provided a primitive way of "resettting" a thread in the event of catastrophic failure, but this hasn't worked in a long time.)
I assume that lazarus() is the function mentioned here. It does seem to try and "reset" a thread in the event of it doing an exit call (lazarus is bound to atexit() calls in the main function).
If that is true, therefore I infer that a possible fix be to remove this function …
> Remove `void lazarus()` from Lisp kernel

- level-1/l1-io.lisp
This fixes ansi-test print-level.8 & print-level.9
Simplified:
```lisp
(defstruct print-level-struct)
(let* ((*print-pretty* nil))
(write-to-string (make-print-level-struct) :level 0   :readably nil))
--> "#"
````
ecl & clasp & clisp respect this, sbcl doesn't
Should the fix be ok, I also have to to change
* https://github.com/Clozure/ccl-tests/blob/master/ansi-tests/print-level.lsp#L94
* https://github.com/Clozure/ccl-tests/blob/master/ansi-tests/print-level.lsp#L107
so that the regression-tests reflect the new behaviour
> treat printing with level 0 for structs without slots

- level-1/l1-numbers.lisp
- lib/numbers.lisp
This allows entering rational numbers as decimals using an `r` exponent marker and/or a `*read-default-float-format*` of `rational`.  Examples:
1.2r0
; => 6/5
(let ((*read-default-float-format* 'rational))
(read-from-string "6.75"))
; => 27/4
[SBCL added this](http://sbcl.org/all-news.html#1.5.2) a while back and I thought it might be nice to have in CCL too.
Corresponding `ccl-tests` PR: https://github.com/Clozure/ccl-tests/pull/4
> Add rational decimal reader syntax

- lib/ccl-export-syms.lisp
- lib/misc.lisp
Fixes GitHub issue Clozure/ccl#215.
SBCL offers SB-ALIEN:GET-ERRNO. CCL has CCL::%GET-ERRNO. We wrap this internal
function in CCL:GET-ERRNO and export this last symbol.
> Add and export CCL:GET-ERRNO

- lisp-kernel/linuxx8632/Makefile
Many Linux distributions now build position independent executables by
default to better support ASLR. This means the text section can be
loaded randomly anywhere in the lower 3G of virtual address space on
32-bit Linux. Many of these addresses cannot be represented as fixnums,
which causes `_SPffcall` to crash early in boot calling a bogus address.
Explicitly disable PIE when building the kernel to avoid this. Fixes
Issue #236.
This is only a partial solution to the problem, however, as shared
libraries may still be loaded at high addresses. See Issue #274 which I
think is a related issue.
> Disable PIE on linuxx8632

- library/loop.lisp
* solves #300 
* This creates an error while macroexpanding. I believe this is correct, but please check.
* Did run the ccl-test aber building a heap image with this change:
```lisp
? (run-tests)
; Warning: Redefining test CCL.ISSUE\#167
; While executing: REGRESSION-TEST::REPORT-ERROR, in process listener(1).
Doing 21908 pending tests of 21908 tests total.
Invoking restart: #<RESTART CL-TEST::FOO #x133C12D>
Invoking restart: #<RESTART CL-TEST::FOO #x133C12D>
Invoking restart: #<RESTART CL-TEST::FOO #x133C12D>
Invoking restart: #<RESTART CL-TEST::FOO #x133C12D>
Invoking restart: #<RESTART CL-TEST::FOO #x133C12D>
=============== All tests succeeded ===============
(FUNCALL DO-TESTS :COMPILE COMPILE :VERBOSE VERBOSE :CATCH-ERRORS T)
took 160,935,936 microseconds (160.935940 seconds) to run. …
```
> loop: Error on invalid by constant 

- lisp-kernel/area.h
- lisp-kernel/gc-common.c
- lisp-kernel/gc.h
- lisp-kernel/pmcl-kernel.c
- lisp-kernel/threads.h
When trying to build CCL kernel I encountered an issue with many object files having conflicting definitions of global C variables, like this:
```
/usr/bin/ld: gc-common.o:/home/jdz/src/ccl/lisp-kernel/linuxx8664/../gc.h:159: multiple definition of `GCndnodes_in_area'; pmcl-kernel.o:/home/jdz/src/ccl/lisp-kernel/linuxx8664/../gc.h:159: first defined here
```
Upon closer look and a short discussion on #ccl I'm pretty sure a bunch of variables in `gc.h` and one variable in `area.h` are "declared" incorrectly (i.e., they are defined, not declared).  So I moved the variables to C files.  I have about zero familiarity of this code, so I might have moved them incorrectly.  There were also two unused variables.
After these changes I could rebuild and run CCL successfully.
Problematic CCL commit: …
> Move global C varibles out of header files

- level-0/l0-aprims.lisp
The make-semaphore function in ccl doesn't have a count argument.
This whenever someone makes a semaphore, they have to call signal
n times to get a positive count.
Count is a field on new_semaphore so just use it...
> Add count argument to semaphore

- lib/macros.lisp
* fixes #326 
* code from the issue by eugeneia
* test in ccl
```lisp
(defstruct af
(value 0 :type fixnum))
(defun af-cas (af old new)
(declare (type af af)
(type fixnum old new)
(optimize (safety 0) (speed 3)))
(ccl::conditional-store (af-value af) old new))
? (setq *foo* (make-af :value 23))
#S(AF :VALUE 23)
? (af-cas *foo* 23 42)
T
? *foo*
#S(AF :VALUE 42)
````
* did also run the regression-tests
```lisp
karsten-poecks-macbook-pro:ccl-tests karstenpoeck$ ../ccl-git-karsten/dx86cl64 -n -l load.lisp
Clozure Common Lisp Version 1.12 (v1.12-dev.3-125-g595a5cf4) DarwinX8664
For more information about CCL, please see http://ccl.clozure.com.
CCL is free software.  It is distributed under the terms of the Apache
Licence, Version 2.0.
? (run-tests)
Doing 21909 pending tests of 21909 tests …
```
> Fix issue 326 by treating "the" in ccl::conditional-store

- doc/manual/ffi.ccldoc
- doc/manual/hemlock.ccldoc
Sun Oct 18 17:28:23 BST 2020
Attempting to build the documentation was failing with:
```lisp
? (defparameter *d* (ccldoc:load-document "ccl:doc;manual;ccl.ccldoc"))
> Error: Unknown form (BLOCK "Tip" (PARA #:|Users of 64-bit platforms may need to pass options such
>                as "-m64" to gcc, may need to give the output library a different
>                extension (such as ".so"), and may need to user slightly different
>                values for other options in order to create an equivalent test
>                library.|))
> While executing: (:INTERNAL CCLDOC::FORM-CLAUSE), in process listener(1).
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Output error text into document and continue
> Type :? for other options.
``` …
> Update "block" to new "text-block"

- lisp-kernel/windows-calls.c
Msys2 Mingw with gcc 10.2.0 no longer has mingw_dosmaperr available, so try to emulate it's logic in dos_maperr. Not sure this is the right thing to do, but something should be done.
> Fix mingw compilation

- cocoa-ide/hemlock/unused/archive/spell/spell-aug.lisp
spell-aug.lisp: defun spell-add-entry was missing a close paren
> fix missing close paren in hemlock unused

- level-0/l0-init.lisp
This commit address the issue [reported here](https://github.com/Clozure/ccl/issues/355).
I wanted to place this in l0-float.lisp, but the PUSHNEW macro seemed to fail. l0-init.lisp is the second most natural spot I can think of adding this feature.
> Add :IEEE-FLOATING-POINT to *FEATURES*

- lisp-kernel/arm-exceptions.h
Bullseye introduced a linking error for multiple definitions of
altivec_available. As far as I can remember altivec is a power pc thing
and not available on arm.
Removing these definitions from the header file fixes the build on
bullseye and continues to work on buster.
> Remove altivec from arm-exceptions.h

- level-1/l1-error-system.lisp
Looking back at the commit history I don't see that this condition was ever defined. Followed the convention used by ABCL, CMUCL, ECL and SBCL in making this condition a control-error subclass.
> Add missing restart-failure condition

- lib/source-files.lisp
This seems to fix the issue but I'm not sure it's the best way. For example it might be better to modify the "Show Callers" dialog so that double-clicking on an item in it always sends a data item to #'find-definition-sources that it knows how to deal with -- that's a less kludgy version of what I'm doing here.
This patch stops the error and the source file opens in the editor, but it doesn't put the cursor on the actual line where the internal definition occurs. You still have to look for that inside the toplevel function where it appears. It would be nice to fix that, but I have a feeling it might require modifications to the source-notes mechanism.
> Patch #'find-definition-sources. Fixes #450.

- compiler/X86/x862.lisp
Following a similar split on the ARM port (see 1257acd50), split
x862-aset2 into two cases, one which handles the needs-memoization
case, and another that handles the other cases.
> split up x862-aset2

- library/sockets.lisp
In #504, we see a problem where a socket is getting unexpectedly closed.
See the comments in the issue for details.
It might make sense to rewrite make-tcp-stream so that it doesn't create a stream at all until we have successfully created and configured the OS-level socket.
> In make-tcp-socket, close stream (not just fd) when connect fails

- library/sockets.lisp
When errors happen during the socket creation process, we want to be able to clean up by closing the socket fd, and not have to worry about leaking an incompletely configured fd into some Lisp object.
> When creating sockets, do all work at fd level first

- lisp-kernel/lisp-debug.c
Compiling with the latest mingw-w64-ucrt_x86_64 this failed to compile as it tries to access the internals of the FILE structure which have been made opaque.
This is my suggested fix.
> Fix access to iobuf internals on Windows

- level-0/l0-cfm-support.lisp
- library/leaks.lisp
- lisp-kernel/arm-exceptions.c
- lisp-kernel/lisp-debug.c
- lisp-kernel/pmcl-kernel.c
- lisp-kernel/ppc-exceptions.c
- lisp-kernel/unix-calls.c
- lisp-kernel/x86-exceptions.c
I hope the commit messages explain the exact changes well enough.
I'm not super happy with the solution for `mcheck.h`, but as I understand it, `start-mtrace` and `stop-mtrace` are intended to be called manually for debugging purposes anyway, so it's not a big deal if the functions exist but fail.
> Support for musl libc under Linux
